spring.application.name=PetCare
spring.jpa.open-in-view=true

spring.datasource.url=jdbc:postgresql://localhost:5432/PetCare
spring.datasource.username=sa
spring.datasource.password=sa123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

logging.file.name=logs/petcare.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n

jwt.secret=minha-chave-super-secreta-para-petcare-com-pelo-menos-32-caracteres
jwt.expiration=86400000